[global]
author         = "jgrelet IRD March 2019 PIRATA-FR29 cruise"
debug          = false
echo           = true
codeRoscop     = 'code_roscop.csv'
roscopSeparator = ','
ASCII          = "ascii"
NETCDF         = "netcdf"
odv            = "odv"
title			= ''
history		= ''
institution = 'IRD'
source = ''
comment = ''
references = ''

[cruise]
CYCLEMESURE    = "PIRATA-FR29"
PLATEFORME     = "THALASSA"
callsign       = "FNFP"
INSTITUTE      = "IRD"
TIMEZONE       = "GMT"
BEGINDATE      = "01/03/2019"
ENDDATE        = "04/04/2019"
PI             = "BOURLES"
CREATOR        = "Jacques.Grelet@ird.fr"

[ctd]
cruisePrefix   = "fr29"
stationPrefixLength  = 3
titleSummary  = "CTD profiles processed during PIRATA-FR29 cruise"
typeInstrument   = "SBE911+"
instrumentNumber  = "09P1263"
dateTimeFormat = "%d/%b/%Y %H:%M:%S"
julianOrigin = 1

	[ctd.header]
	isHeader = '^[*#]+\s+'
	endHeader = '^[*]END[*]'
	station = 'Station\s*:\s*\D*(\d*)'
	DATETIME = 'System UpLoad Time\s*=\s*(\w+)\s+(\d+)\s+(\d+)\s+(\d+):(\d+):(\d+)'
	LATITUDE = 'NMEA\s+Latitude\s*[:=]\s*(\d+)\s+(\d+\.\d+)\s+(\w)'
	LONGITUDE = 'NMEA\s+Longitude\s*[:=]\s*(\d+)\s+(\d+.\d+)\s+(\w)'
	DATE = 'Date\s*:\s*(\d+)/(\d+)/(\d+)'
	TIME = '[Heure|Hour]\s*:\s*(\d+)[:hH](\d+):(\d+)'
	BATH = 'Bottom Depth\s*:\s*(\d*\.?\d+?)\s*\S*'
	operator = 'Operator\s*:\s*(.*)'
	type = 'Type\s*:\s*(.*)'

[btl]
typeInstrument           = "SBE32 standard 24 Niskin bottles"
instrumentNumber         = "unknown"
titleSummary   = "Water sample during PIRATA-FR32 cruise with 22 levels"
comment        = "CTD bottles water sampling with temperature, salinity and oxygen from primary and secondary sensors"
dateTimeFormat = "%d/%b/%Y %H:%M:%S"
julianOrigin = 1
skipLineWith = "(sdev)"

	[btl.header]
	endHeader = '^\s+Position\s+Time\s+$'
	station = 'Station\s*:\s*\D*(\d*)'
	DATETIME = 'System UpLoad Time\s*=\s*(\w+)\s+(\d+)\s+(\d+)\s+(\d+):(\d+):(\d+)'
	LATITUDE = 'NMEA\s+Latitude\s*[:=]\s*(\d+)\s+(\d+\.\d+)\s+(\w)'
	LONGITUDE = 'NMEA\s+Longitude\s*[:=]\s*(\d+)\s+(\d+.\d+)\s+(\w)'
	DATE = 'Date\s*:\s*(\d+)/(\d+)/(\d+)'
	TIME = '[Heure|Hour]\s*:\s*(\d+)[:hH](\d+):(\d+)'
	BATH = 'Bottom Depth\s*:\s*(\d*\.?\d+?)\s*\S*'
	operator = 'Operator\s*:\s*(.*)'
	type = 'Type\s*:\s*(.*)'

[sbe35]
typeInstrument           = "SBE35 high precision realtime thermometer"
instrumentNumber         = 102


    [sbe35.header]
	endHeader = '^dd\d+,\d+$'
	#station = '^[*]\s+FileName\s+=\s+(.*)$'
        station = '^[*]+\s+Station:(\d+)$'

[xbt]
cruisePrefix   = "fr29"
stationPrefixLength  = 3
typeInstrument   = "SIPPICAN+"
instrumentNumber  = "N/A"
acquisitionSoftware = "WinMK21"
acquisitionVersion = "2.10.1" 
processingSoftware = ""
processingVersion = ""
dateTimeFormat = "%d/%m/%Y %H:%M:%S"
type           = "SIPPICAN"
sn             = "01150"
title_summary  = "XBT profiles processed during PIRATA-FR29 cruise"
comment        = "Extract from .edf files"

	[xbt.header]
	endHeader = '^Depth\s*\(m\)'
	station = 'Sequence\s*#\s*:\s*(\d*)'
	TIME = 'Time of Launch\s*[:=]\s*(\d+):(\d+):(\d+)'
	DATE = 'Date of Launch\s*[:=]\s*(\d+)/(\d+)/(\d+)'
	DATETIME = 'System UpLoad Time\s*=\s*(\w+)\s+(\d+)\s+(\d+)\s+(\d+):(\d+):(\d+)'
	LATITUDE = 'Latitude\s*[:=]\s*(\d+)\s+(\d+\.\d+)(\w)'
	LONGITUDE = 'Longitude\s*[:=]\s*(\d+)\s+(\d+.\d+)(\w)'

[ladcp]
cruisePrefix   = "fr29"
stationPrefixLength  = 3
typeInstrument   = "LADCP WH150/WH300"
instrumentNumber  = "24543/24085"
acquisitionSoftware = "BBTALK"
acquisitionVersion = 3.04
processingSoftware = "MATLAB-VISBECK"
processingVersion = "10.16.2"
title_summary  = "IFM-GEOMAR/LDEO Matlab LADCP-Processing system adapted by FM/PR/JG"
comment        = "Extract from .lad files"

	[ladcp.header]
	station = 'fr29(\d*)'
	endHeader = 'Columns'
	DATE = 'Date\s*=\s*(\d+)/(\d+)/(\d+)'
	TIME = 'Start_Time\s*=\s*(\d+)[:hH](\d+):(\d+)'
	LATITUDE = 'Latitude\s*[:=]\s*([-+]?\d+\.\d+)'
	LONGITUDE = 'Longitude\s*[:=]\s*([-]?\d+.\d+)'

[tsg]
cruisePrefix   = "fr29"
stationPrefixLength  = 3 
separator = ","
typeInstrument   = "SBE21"
instrumentNumber  = "3199"
acquisitionSoftware = "COLCOR"
acquisitionVersion = ""
processingSoftware = ""
processingVersion = ""
calDate        = "14/01/2019" 
externalType   = "SBE3S"
externalSn     = 4074
externalCalDate = "16/01/2018"
depth_intake   = 4
title_summary  = "Thermosalinograph data acquired with Seabird SBE21 instrument and reduce with THECSAS/COLCOR"
comment        = "Extract from .colcor files"

	[tsg.header]
	isHeader = '^#'
	isData = 'PIFM,TSCOR'

	[tsg.format]
	TIME = '(\d+):(\d+):(\d+)'
	DATE = '(\d+)/(\d+)/(\d+)'
	LATITUDE = '([NS]),(\d+),(\d+\.\d+)'
	LONGITUDE = '([EW]),(\d+),(\d+\.\d+)'

[casino]
separator = "	"
acquisitionSoftware = "CASINO"
acquisitionVersion = ""
processingSoftware = ""
processingVersion = ""
title_summary  = "Raw data extract from CASINO software, sample interval 30 secondes"
comment        = "Extract from .csv files"
#dateTimeFormat = "%d/%b/%Y %H:%M:%S"


	[casino.header]
	isHeader = '^#'
	isData = 'ACQAUTO'

	[casino.format]
	TIME = '(\d+):(\d+):(\d+)'
	DATE = '(\d+)/(\d+)/(\d+)'

[split]
	[split.ctd]
	ETDD = 1
	PRES = 2
	DEPTH = 3
	TEMP = 4
	PSAL = 17
	DENS = 19
	SVEL = 21
	DOX2 = 15
	FLU2 = 13
	FLU3 = 14
	TUR3 = 12
	NAVG = 23

	[split.ctdAll]
	ETDD = 1
	PRES = 2
	DEPTH = 3
	TE01 = 4
	TE02 = 5
	CND1 = 6
	CND2 = 7
	DOV1 = 8
	DOV2 = 9
	DVT1 = 10
	DVT2 = 11
	TUR3 = 12
	FLU2 = 13
	FLU3 = 14
	DO12 = 15
	DO22 = 16
	PSA1 = 17
	PSA2 = 18
	DEN1 = 19
	DEN2 = 20
	SVEL = 21
	NAVG = 23

	[split.btl]
	BOTL = 0
	PSA1 = 4
	PSA2 = 5
	DO11 = 6
	DO12 = 7
	DO21 = 8
	DO22 = 9
	Potemp090C = 10
	Potemp190C = 11
	ETDD = 12
	PRES = 13
	DEPTH = 14
	TE01 = 15
	TE02 = 16
	CND1 = 17
	CND2 = 18
	DOV1 = 19
	DOV2 = 20
	DVT1 = 21
	DVT2 = 22
	TUR3 = 23
	FLU2 = 24

	[split.sb35]
	BOTL = 0
	TE35 = 16

	
[split.xbt]
	DEPTH = 0
	TEMP = 1
	SVEL = 2	

[split.ladcp]
	DEPTH = 0
	EWCT = 1
	NSCT = 2

[split.tsg]
	SSJT = 18
	SSTP = 19
	SSPS = 21

[split.casino]
	LATITUDE = 2
	LONGITUDE = 3
	BATH = 35
	SSTP = 94
	SSJT = 95
	SSPS = 96
	WMSP = 65
	WDIR = 64
	DRYT = 66
	RELH = 68
